// src/mockData/bikes.js

export const MOCK_BIKES = [
  // --- DỮ LIỆU CŨ (GIỮ NGUYÊN) ---
  {
    id: 1,
    name: "Trek Marlin 7 Gen 2 (2022)",
    price: 12500000,
    originalPrice: 15500000,
    brand: "Trek",
    type: "MTB",
    condition: 98,
    location: "Đống Đa, Hà Nội",
    image:
      "https://fxbike.vn/wp-content/uploads/2022/02/Trek-Marlin-7-2022-1-600x450.jpeg",
    postedTime: "2 giờ trước",
    inspectorChecked: true,
    seller: { name: "Nguyễn Văn A", avatar: "https://i.pravatar.cc/150?u=1" },
    year: 2022,
    frame: "M",
    wheel: "29 inch",
    brake: "Phanh đĩa dầu Shimano MT200",
    gears: "1x10 Shimano Deore",
    weight: 13.5,
    description:
      "Xe MTB quốc dân, màu xanh cực đẹp. Phù hợp người cao 1m65-1m75. Đã nâng cấp pedal bạc đạn và grip êm tay.",
  },
  {
    id: 2,
    name: "Giant Escape 2 City Disc",
    price: 8200000,
    originalPrice: 10500000,
    brand: "Giant",
    type: "Touring",
    condition: 95,
    location: "Q.1, TP. Hồ Chí Minh",
    image:
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=600&q=80",
    postedTime: "5 giờ trước",
    inspectorChecked: true,
    seller: { name: "Trần Bảo B", avatar: "https://i.pravatar.cc/150?u=2" },
    year: 2021,
    frame: "S",
    wheel: "700c",
    brake: "Phanh đĩa cơ Tektro",
    gears: "2x8 Shimano Altus",
    weight: 11.2,
    description:
      "Dòng touring đi phố nhẹ nhàng, có baga chắn bùn zin theo xe. Xe chính chủ đi làm hàng ngày, bảo dưỡng định kỳ.",
  },
  {
    id: 3,
    name: "Specialized Allez E5 Sport",
    price: 21000000,
    originalPrice: 25000000,
    brand: "Specialized",
    type: "Road",
    condition: 99,
    location: "Hải Châu, Đà Nẵng",
    image:
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80",
    postedTime: "1 ngày trước",
    inspectorChecked: false,
    seller: { name: "Lê C", avatar: "https://i.pravatar.cc/150?u=3" },
    year: 2020,
    frame: "52",
    wheel: "700c",
    brake: "Phanh vành Axis",
    gears: "2x9 Shimano Sora",
    weight: 9.5,
    description:
      "Khung nhôm E5 cao cấp của Specialized, phuộc carbon. Xe còn rất mới, chưa đâm đụng, sơn zin nguyên bản.",
  },
  {
    id: 4,
    name: "Trinx M136 Pro (2023)",
    price: 3500000,
    originalPrice: 4200000,
    brand: "Trinx",
    type: "MTB",
    condition: 90,
    location: "Thanh Xuân, Hà Nội",
    image:
      "https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&w=600&q=80",
    postedTime: "30 phút trước",
    inspectorChecked: true,
    seller: { name: "Hoàng D", avatar: "https://i.pravatar.cc/150?u=4" },
    year: 2023,
    frame: "17 inch",
    wheel: "26 inch",
    brake: "Phanh đĩa cơ",
    gears: "3x7 Shimano Tourney",
    weight: 14.5,
    description:
      "Xe giá rẻ cho học sinh sinh viên, cấu hình đủ dùng đi học, đi chơi. Có xước dăm nhẹ ở khung do gửi xe.",
  },
  {
    id: 5,
    name: "Cannondale Trail 5",
    price: 14500000,
    originalPrice: 18000000,
    brand: "Cannondale",
    type: "MTB",
    condition: 96,
    location: "Thủ Đức, TP. HCM",
    image:
      "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=600&q=80",
    postedTime: "3 ngày trước",
    inspectorChecked: true,
    seller: { name: "Phạm E", avatar: "https://i.pravatar.cc/150?u=5" },
    year: 2021,
    frame: "L",
    wheel: "29 inch",
    brake: "Phanh đĩa dầu Tektro",
    gears: "2x10 Shimano Deore",
    weight: 13.8,
    description:
      "Thương hiệu Mỹ, khung sườn bảo hành trọn đời. Màu xám xi măng hot trend. Phuộc nhún êm ái.",
  },
  {
    id: 6,
    name: "Pinarello Dogma F12 (Frame Only)",
    price: 85000000,
    originalPrice: 120000000,
    brand: "Pinarello",
    type: "Road",
    condition: 99,
    location: "Q.3, TP. Hồ Chí Minh",
    image:
      "https://pinarello.com/storage/Article/c43ba97463a91e8215b71d134aed6184.jpg",
    postedTime: "1 tuần trước",
    inspectorChecked: true,
    seller: { name: "Đại Gia F", avatar: "https://i.pravatar.cc/150?u=6" },
    year: 2020,
    frame: "50",
    wheel: "700c (Tương thích)",
    brake: "Phanh vành (Direct Mount)",
    gears: "N/A",
    weight: 0.8,
    description:
      "Chỉ bán khung sườn (Frame set) Dogma F12 hàng chính hãng, bao check serial. Kèm cọc yên, ghi đông Most Talon.",
  },
  {
    id: 7,
    name: "Galaxy ML200",
    price: 2800000,
    originalPrice: 3500000,
    brand: "Galaxy",
    type: "MTB",
    condition: 85,
    location: "Cầu Giấy, Hà Nội",
    image:
      "https://fxbike.vn/wp-content/uploads/2023/10/Xe-Dap-Galaxy-ML200-2024-2-3.jpg",
    postedTime: "4 giờ trước",
    inspectorChecked: false,
    seller: { name: "Sinh Viên G", avatar: "https://i.pravatar.cc/150?u=7" },
    year: 2022,
    frame: "17 inch",
    wheel: "26 inch",
    brake: "Phanh đĩa cơ",
    gears: "3x8 Shimano",
    weight: 15.0,
    description:
      "Xe đạp thể thao giá rẻ, khung nhôm, phù hợp tập thể dục nhẹ nhàng. Lốp sau hơi mòn.",
  },
  {
    id: 8,
    name: "Cervélo S5 Disc",
    price: 110000000,
    originalPrice: 140000000,
    brand: "Cervélo",
    type: "Road",
    condition: 97,
    location: "Tây Hồ, Hà Nội",
    image:
      "https://images.unsplash.com/photo-1559348349-86f1f65817fe?auto=format&fit=crop&w=600&q=80",
    postedTime: "2 ngày trước",
    inspectorChecked: true,
    seller: { name: "Hùng H", avatar: "https://i.pravatar.cc/150?u=8" },
    year: 2023,
    frame: "54",
    wheel: "700c",
    brake: "Phanh đĩa dầu Dura-Ace",
    gears: "2x12 Shimano Dura-Ace Di2",
    weight: 7.8,
    description:
      "Siêu phẩm Aero, group điện cao cấp nhất. Xe như mới khui thùng, chủ cũ đi cafe là chính.",
  },

  // --- DỮ LIỆU MỚI (THÊM VÀO) ---
  {
    id: 9,
    name: "Twitter R10 Carbon",
    price: 10500000,
    originalPrice: 13900000,
    brand: "Twitter",
    type: "Road",
    condition: 98,
    location: "Gò Vấp, TP. HCM",
    image:
      "https://xedapgiakho.com/wp-content/uploads/2024/06/xe-dap-dua-twitter-r10-retrospec-rs-22-4.jpg",
    postedTime: "30 phút trước",
    inspectorChecked: false,
    seller: { name: "Tuấn K", avatar: "https://i.pravatar.cc/150?u=9" },
    year: 2022,
    frame: "48",
    wheel: "700c",
    brake: "Phanh đĩa dầu",
    gears: "2x11 Retrospec",
    weight: 8.5,
    description:
      "Khung carbon siêu nhẹ, dây đi âm sườn toàn bộ. Xe lướt mới đi được 500km.",
  },
  {
    id: 10,
    name: "Dahon K3 Plus (Xe Gấp)",
    price: 11500000,
    originalPrice: 14500000,
    brand: "Dahon",
    type: "Touring",
    condition: 95,
    location: "Hoàn Kiếm, Hà Nội",
    image:
      "https://hellobike.vn/wp-content/uploads/2025/07/xe-ap-gap-gon-dahon-k3-001.jpg",
    postedTime: "6 giờ trước",
    inspectorChecked: true,
    seller: { name: "Minh Nhật", avatar: "https://i.pravatar.cc/150?u=10" },
    year: 2021,
    frame: "Free size",
    wheel: "16 inch",
    brake: "Phanh đĩa",
    gears: "9 Speed",
    weight: 9.8,
    description:
      "Xe gấp gọn bỏ cốp ô tô tiện lợi. Đã độ nhiều đồ chơi: tay nắm, yên Brooks, pedal tháo rời.",
  },
  {
    id: 11,
    name: "Jett Cycles Strada Comp",
    price: 4500000,
    originalPrice: 6000000,
    brand: "Jett",
    type: "MTB",
    condition: 88,
    location: "Thủ Dầu Một, Bình Dương",
    image:
      "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=600&q=80",
    postedTime: "1 ngày trước",
    inspectorChecked: false,
    seller: { name: "Quốc Bảo", avatar: "https://i.pravatar.cc/150?u=11" },
    year: 2019,
    frame: "M",
    wheel: "27.5 inch",
    brake: "Phanh đĩa cơ",
    gears: "3x8 Shimano Altus",
    weight: 14.2,
    description:
      "Xe cũ theo thời gian nhưng khung sườn còn rất chắc chắn. Thích hợp cho người mới tập MTB.",
  },
  {
    id: 12,
    name: "Bianchi Nirone 7",
    price: 18500000,
    originalPrice: 28000000,
    brand: "Bianchi",
    type: "Road",
    condition: 92,
    location: "Q.7, TP. Hồ Chí Minh",
    image:
      "https://product.hstatic.net/200000832795/product/z5697948149137_6649faef31d52d224c7b041ae2f6a298_3dc29bf950544af3909f4237c92705f7_master.jpg",
    postedTime: "3 giờ trước",
    inspectorChecked: true,
    seller: { name: "Sarah Nguyễn", avatar: "https://i.pravatar.cc/150?u=12" },
    year: 2018,
    frame: "50",
    wheel: "700c",
    brake: "Phanh vành Bianchi",
    gears: "2x10 Shimano Tiagra",
    weight: 9.2,
    description:
      "Màu xanh Celeste huyền thoại của Bianchi. Xe nhập Ý, giấy tờ đầy đủ.",
  },
  {
    id: 13,
    name: "Fixed Gear Aventon Mataro",
    price: 6800000,
    originalPrice: 9500000,
    brand: "Other",
    type: "Road",
    condition: 90,
    location: "Hai Bà Trưng, Hà Nội",
    image:
      "https://file.hstatic.net/200000051564/file/aventon_mataro_2020_3a0aefe961a74b238611ccb9905bbf3c.png",
    postedTime: "12 giờ trước",
    inspectorChecked: false,
    seller: { name: "Hải Fixie", avatar: "https://i.pravatar.cc/150?u=13" },
    year: 2020,
    frame: "52",
    wheel: "700c",
    brake: "Không phanh (Fixed)",
    gears: "1 Speed (48T/16T)",
    weight: 9.0,
    description:
      "Xe Fixed Gear khung nhôm bản dẹt khí động học. Đã thay xích hạt đậu, strap zin.",
  },
  {
    id: 14,
    name: "Peugeot Course Vintage (1980s)",
    price: 15000000,
    originalPrice: 0,
    brand: "Peugeot",
    type: "Road",
    condition: 85,
    location: "Huế",
    image:
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80",
    postedTime: "5 ngày trước",
    inspectorChecked: true,
    seller: { name: "Bác Ba", avatar: "https://i.pravatar.cc/150?u=14" },
    year: 1985,
    frame: "54 (Thép)",
    wheel: "700c",
    brake: "Phanh Mafac",
    gears: "2x6 Simplex",
    weight: 11.5,
    description:
      "Xe đạp cổ Peugeot sườn thép rắc co, sơn zin tem zin. Dành cho người sưu tầm hoài cổ.",
  },
  {
    id: 15,
    name: "Giant XTC 800",
    price: 13200000,
    originalPrice: 16500000,
    brand: "Giant",
    type: "MTB",
    condition: 97,
    location: "Biên Hòa, Đồng Nai",
    image:
      "https://giantvietnam.vn/wp-content/uploads/2023/09/2024-XTC-800-Reu-27.5-scaled.jpg",
    postedTime: "45 phút trước",
    inspectorChecked: true,
    seller: { name: "Thành Đạt", avatar: "https://i.pravatar.cc/150?u=15" },
    year: 2022,
    frame: "M",
    wheel: "27.5 inch",
    brake: "Phanh đĩa dầu Shimano",
    gears: "1x12 Shimano SLX",
    weight: 12.8,
    description:
      "Dòng MTB cao cấp của Giant, khung nhôm Aluxx SL siêu nhẹ. Phuộc hơi có khóa remote.",
  },
  {
    id: 16,
    name: "Asama Solano 2.0",
    price: 3200000,
    originalPrice: 4800000,
    brand: "Asama",
    type: "Road",
    condition: 89,
    location: "Q. Bình Thạnh, TP. HCM",
    image:
      "https://salt.tikicdn.com/ts/tmp/9f/b4/f9/f33ff0fc950ec0e2fffbb8f47a53094a.jpg",
    postedTime: "2 ngày trước",
    inspectorChecked: false,
    seller: { name: "Em Gái", avatar: "https://i.pravatar.cc/150?u=16" },
    year: 2020,
    frame: "48",
    wheel: "700c",
    brake: "Phanh vành",
    gears: "2x7 Shimano Tourney",
    weight: 11.0,
    description:
      "Xe road city giá rẻ, thích hợp đi học đi làm. Đã thay cặp lốp mới.",
  },
  {
    id: 17,
    name: "Java Siluro 3",
    price: 12000000,
    originalPrice: 16000000,
    brand: "Other",
    type: "Road",
    condition: 96,
    location: "Nha Trang, Khánh Hòa",
    image:
      "https://images.unsplash.com/photo-1618762044398-ec1e7e048bbd?auto=format&fit=crop&w=600&q=80",
    postedTime: "1 ngày trước",
    inspectorChecked: true,
    seller: { name: "Vinh Java", avatar: "https://i.pravatar.cc/150?u=17" },
    year: 2021,
    frame: "50",
    wheel: "700c (Vành cao 4cm)",
    brake: "Phanh đĩa cáp bán thủy lực",
    gears: "2x9 Shimano Sora",
    weight: 10.5,
    description:
      "Thiết kế khí động học hầm hố, dây âm 100%. Màu tem tôm hùm độc lạ.",
  },
  {
    id: 18,
    name: "Merida Scultura 400",
    price: 19500000,
    originalPrice: 24000000,
    brand: "Merida",
    type: "Road",
    condition: 98,
    location: "Hà Đông, Hà Nội",
    image:
      "https://www.cyclelab.com/uploads/products/C8383757-F810-410D-9759-D7940772639A.png",
    postedTime: "8 giờ trước",
    inspectorChecked: true,
    seller: { name: "Tiến Dũng", avatar: "https://i.pravatar.cc/150?u=18" },
    year: 2021,
    frame: "52",
    wheel: "700c",
    brake: "Phanh vành 105",
    gears: "2x11 Shimano 105 R7000",
    weight: 8.9,
    description:
      "Full group 105 R7000 cực ngon trong tầm giá. Xe giữ gìn kỹ, không một vết xước.",
  },
  {
    id: 19,
    name: "Xe đạp trợ lực Xiaomi Himo Z20",
    price: 9800000,
    originalPrice: 14000000,
    brand: "Other",
    type: "Touring",
    condition: 94,
    location: "Q.2, TP. HCM",
    image:
      "https://bizweb.dktcdn.net/thumb/1024x1024/100/513/392/products/xe-dap-tro-luc-dien-himo-z20.jpg?v=1760514231880",
    postedTime: "10 giờ trước",
    inspectorChecked: true,
    seller: { name: "Tech Bike", avatar: "https://i.pravatar.cc/150?u=19" },
    year: 2022,
    frame: "Gấp gọn",
    wheel: "20 inch",
    brake: "Phanh đĩa",
    gears: "6 Speed Shimano",
    weight: 21.6,
    description:
      "Xe đạp trợ lực điện, pin còn tốt chạy được 50km/lần sạc. Gấp gọn bỏ thang máy chung cư.",
  },
  {
    id: 20,
    name: "Giant Revolt Advanced 2 (Gravel)",
    price: 35000000,
    originalPrice: 42000000,
    brand: "Giant",
    type: "Road",
    condition: 99,
    location: "Đà Lạt, Lâm Đồng",
    image:
      "https://xedapso.com/wp-content/smush-webp/2025/01/xe-dap-dua-Giant-Revolt-Adv-2-ban-2025-mau-den.jpg.webp",
    postedTime: "30 phút trước",
    inspectorChecked: true,
    seller: { name: "Lâm Gravel", avatar: "https://i.pravatar.cc/150?u=20" },
    year: 2023,
    frame: "M (Carbon)",
    wheel: "700x38c",
    brake: "Phanh đĩa dầu GRX",
    gears: "2x11 Shimano GRX",
    weight: 9.3,
    description:
      "Dòng Gravel chuyên trị đường xấu, khung carbon phuộc D-Fuse giảm chấn. Xe mới chạy roda.",
  },
  {
    id: 21,
    name: "Tsunami SNM100 (Fixed Gear)",
    price: 5500000,
    originalPrice: 7200000,
    brand: "Tsunami",
    type: "Road", // Fixed Gear thường xếp vào Road hoặc City
    condition: 95,
    location: "Thanh Xuân, Hà Nội",
    image:
      "https://www.mrbicycles.com/wp-content/uploads/2021/07/TSUNAMI-SNM100-Complete-bike-Black-Drop-bar-1.jpg",
    postedTime: "1 giờ trước",
    inspectorChecked: true,
    seller: { name: "Đức Fixed", avatar: "https://i.pravatar.cc/150?u=21" },
    year: 2023,
    frame: "52 (Nhôm)",
    wheel: "700c",
    brake: "Không phanh",
    gears: "1 Speed (48T/17T)",
    weight: 9.0,
    description:
      "Màu bạc (Silver) cực cháy. Đã lên đùi đĩa Legend, xích hạt đậu. Tặng kèm strap và rọ chân.",
  },
  {
    id: 22,
    name: "Giant Momentum iNeed Latte 26",
    price: 7200000,
    originalPrice: 9500000,
    brand: "Giant",
    type: "City",
    condition: 98,
    location: "Q.3, TP. Hồ Chí Minh",
    image:
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=600&q=80", // Ảnh minh họa xe city
    postedTime: "2 giờ trước",
    inspectorChecked: false,
    seller: { name: "Lan Chi", avatar: "https://i.pravatar.cc/150?u=22" },
    year: 2022,
    frame: "S (Nữ)",
    wheel: "26 inch",
    brake: "Phanh vành",
    gears: "7 Speed Shimano",
    weight: 12.5,
    description:
      "Xe đạp thời trang cho nữ, có khay đựng cốc cafe rất xinh. Xe mới đi vài lần chụp ảnh, còn như mới.",
  },
  {
    id: 23,
    name: "Trek Domane AL 2 Disc",
    price: 18500000,
    originalPrice: 24000000,
    brand: "Trek",
    type: "Road",
    condition: 96,
    location: "Sơn Trà, Đà Nẵng",
    image:
      "https://product.hstatic.net/200000887845/product/domaneal2disc_23_33083_b_primary_5656cfcc59d84a75b60c47763d55f8b7.jpg",
    postedTime: "30 phút trước",
    inspectorChecked: true,
    seller: { name: "Minh Trek", avatar: "https://i.pravatar.cc/150?u=23" },
    year: 2021,
    frame: "54",
    wheel: "700c",
    brake: "Phanh đĩa cơ Tektro",
    gears: "2x8 Shimano Claris",
    weight: 10.5,
    description:
      "Dòng Endurance đi đường dài cực êm. Sơn zin không trầy xước. Đã bảo dưỡng toàn bộ trục.",
  },
  {
    id: 24,
    name: "California City 200",
    price: 3200000,
    originalPrice: 4500000,
    brand: "Other",
    type: "Touring",
    condition: 90,
    location: "Hà Đông, Hà Nội",
    image:
      "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=600&q=80",
    postedTime: "1 ngày trước",
    inspectorChecked: false,
    seller: { name: "Shop Xe Cũ", avatar: "https://i.pravatar.cc/150?u=24" },
    year: 2020,
    frame: "M",
    wheel: "700c",
    brake: "Phanh cơ",
    gears: "3x7 Shimano",
    weight: 13.0,
    description:
      "Xe đạp thành phố giá rẻ, chắn bùn baga đầy đủ. Phù hợp đi học, đi chợ. Mọi chức năng hoạt động tốt.",
  },
  {
    id: 25,
    name: "Sava X9 (Full Carbon)",
    price: 16500000,
    originalPrice: 22000000,
    brand: "Sava",
    type: "MTB",
    condition: 97,
    location: "Biên Hòa, Đồng Nai",
    image:
      "https://bizweb.dktcdn.net/100/412/747/products/xe-dap-sava-x9-den.jpg?v=1700020756287",
    postedTime: "5 giờ trước",
    inspectorChecked: true,
    seller: { name: "Hùng Carbon", avatar: "https://i.pravatar.cc/150?u=25" },
    year: 2022,
    frame: "17 inch (Carbon)",
    wheel: "27.5 inch",
    brake: "Phanh đĩa dầu",
    gears: "3x10 Shimano Deore",
    weight: 11.5,
    description:
      "Khung carbon siêu nhẹ, không mối hàn. Phuộc hơi êm ái. Xe chính chủ đập hộp.",
  },
  {
    id: 26,
    name: "Brompton M6L (Black Lacquer)",
    price: 45000000,
    originalPrice: 55000000,
    brand: "Other",
    type: "Touring", // Xe gấp
    condition: 99,
    location: "Hoàn Kiếm, Hà Nội",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvE67aGnCIGRuhOysUv12c_btoyTrDbuCEWQ&s",
    postedTime: "3 ngày trước",
    inspectorChecked: true,
    seller: { name: "Mr. Lee", avatar: "https://i.pravatar.cc/150?u=26" },
    year: 2021,
    frame: "Thép (Gấp)",
    wheel: "16 inch",
    brake: "Phanh vành",
    gears: "6 Speed",
    weight: 11.8,
    description:
      "Vua của các dòng xe gấp. Màu Black Lacquer lộ mối hàn đồng cực hiếm. Xe sưu tầm, chưa lăn bánh nhiều.",
  },
  {
    id: 27,
    name: "Louis Garneau LGS-CH",
    price: 5800000,
    originalPrice: 8500000,
    brand: "Louis Garneau",
    type: "Touring",
    condition: 88,
    location: "Q.7, TP. HCM",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJNdBlshAvypFo7908eEwDdhem-fiduBjPOA&s",
    postedTime: "7 giờ trước",
    inspectorChecked: false,
    seller: { name: "An Japan", avatar: "https://i.pravatar.cc/150?u=27" },
    year: 2018,
    frame: "47",
    wheel: "700c",
    brake: "Phanh Shimano",
    gears: "3x8 Shimano Altus",
    weight: 11.0,
    description:
      "Xe bãi Nhật xịn, thương hiệu Canada. Khung nhôm 6061 bền bỉ. Đã thay cặp lốp Kenda mới.",
  },
  {
    id: 28,
    name: "Chevaux Toto (2024)",
    price: 6200000,
    originalPrice: 7500000,
    brand: "Other",
    type: "MTB",
    condition: 99,
    location: "Vinh, Nghệ An",
    image:
      "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?auto=format&fit=crop&w=600&q=80",
    postedTime: "20 phút trước",
    inspectorChecked: true,
    seller: { name: "Đại Lý Xe Đạp", avatar: "https://i.pravatar.cc/150?u=28" },
    year: 2024,
    frame: "16 inch",
    wheel: "27.5 inch",
    brake: "Phanh dầu Shimano MT200",
    gears: "3x8 Shimano Altus",
    weight: 14.0,
    description:
      "Xe mới 99%, khách mua về vợ không cho đi nên bán lại. Cấu hình ngon nhất tầm giá 6 triệu.",
  },
  {
    id: 29,
    name: "Specialized S-Works Tarmac SL7",
    price: 185000000,
    originalPrice: 280000000,
    brand: "Specialized",
    type: "Road",
    condition: 98,
    location: "Thảo Điền, TP. HCM",
    image:
      "https://images.unsplash.com/photo-1559348349-86f1f65817fe?auto=format&fit=crop&w=600&q=80",
    postedTime: "1 tuần trước",
    inspectorChecked: true,
    seller: { name: "Pro Rider", avatar: "https://i.pravatar.cc/150?u=29" },
    year: 2022,
    frame: "52",
    wheel: "Roval Rapide CLX",
    brake: "SRAM Red AXS",
    gears: "2x12 SRAM Red eTap",
    weight: 6.8,
    description:
      "Siêu phẩm đua chuyên nghiệp. Màu Green Tint đắt tiền. Xe bao test tại hãng, không một lỗi nhỏ.",
  },
  {
    id: 30,
    name: "Thống Nhất New 26",
    price: 1500000,
    originalPrice: 2200000,
    brand: "Thống Nhất",
    type: "City",
    condition: 85,
    location: "Cầu Giấy, Hà Nội",
    image:
      "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=600&q=80",
    postedTime: "2 ngày trước",
    inspectorChecked: false,
    seller: { name: "Bác Bảo vệ", avatar: "https://i.pravatar.cc/150?u=30" },
    year: 2019,
    frame: "Thép",
    wheel: "26 inch",
    brake: "Phanh cơ",
    gears: "1 Speed",
    weight: 16.0,
    description:
      "Xe nồi đồng cối đá, đi chợ đi làm vô tư. Đã thay yên mới ngồi rất êm.",
  },
  {
    id: 31,
    name: "Bianchi Oltre XR4 Disc",
    price: 95000000,
    originalPrice: 130000000,
    brand: "Bianchi",
    type: "Road",
    condition: 96,
    location: "Hải Phòng",
    image:
      "https://www.serviziocorsa.com/media/image/product/21392/md/en-bianchi-oltre-xr4-disc-super-record-eps.jpg",
    postedTime: "4 ngày trước",
    inspectorChecked: true,
    seller: { name: "Dũng Bianchi", avatar: "https://i.pravatar.cc/150?u=31" },
    year: 2021,
    frame: "53",
    wheel: "Fulcrum Racing",
    brake: "Shimano Ultegra",
    gears: "2x11 Shimano Ultegra R8000",
    weight: 7.5,
    description:
      "Công nghệ Countervail chống rung độc quyền. Xe Ý chính hãng, màu Celeste đặc trưng.",
  },
  {
    id: 32,
    name: "XDS K500",
    price: 6500000,
    originalPrice: 8500000,
    brand: "Other",
    type: "MTB",
    condition: 95,
    location: "Bình Thạnh, TP. HCM",
    image:
      "https://hellobike.vn/wp-content/uploads/2025/03/xe-dap-xds-rs500-bac-1000x667-1-900x600.jpg",
    postedTime: "9 giờ trước",
    inspectorChecked: true,
    seller: { name: "Shop 2Hand", avatar: "https://i.pravatar.cc/150?u=32" },
    year: 2022,
    frame: "17 inch (X6 Aluminum)",
    wheel: "27.5 inch",
    brake: "Phanh dầu Magura",
    gears: "3x9 Shimano Altus",
    weight: 13.5,
    description:
      "Khung nhôm X6 siêu nhẹ và cứng (công nghệ dùng trong hàng không). Xe lướt đẹp.",
  },
  {
    id: 33,
    name: "Peugeot Colibri 16 (Cổ)",
    price: 8500000,
    originalPrice: 0,
    brand: "Peugeot",
    type: "Touring",
    condition: 80,
    location: "Huế",
    image:
      "https://kaitori.buychari.com/kaitori-sys/wp-content/uploads/2023/05/5223043000705-1-880x587.jpg",
    postedTime: "1 tuần trước",
    inspectorChecked: false,
    seller: { name: "Chú Tư", avatar: "https://i.pravatar.cc/150?u=33" },
    year: 1990,
    frame: "Thép",
    wheel: "16 inch",
    brake: "Phanh càng cua",
    gears: "5 Speed",
    weight: 12.0,
    description:
      "Xe đạp cổ Peugeot màu vàng chanh. Sơn zin tem zin có trầy xước theo thời gian. Đáng sưu tầm.",
  },
  {
    id: 34,
    name: "Giant TCR Advanced Pro 1",
    price: 42000000,
    originalPrice: 65000000,
    brand: "Giant",
    type: "Road",
    condition: 94,
    location: "Q.10, TP. HCM",
    image:
      "https://images.unsplash.com/photo-1559348349-86f1f65817fe?auto=format&fit=crop&w=600&q=80",
    postedTime: "12 giờ trước",
    inspectorChecked: true,
    seller: { name: "Thắng TCR", avatar: "https://i.pravatar.cc/150?u=34" },
    year: 2020,
    frame: "M",
    wheel: "Carbon SLR 1",
    brake: "Phanh vành",
    gears: "2x11 Shimano Ultegra",
    weight: 7.2,
    description:
      "Vua leo đèo. Vành carbon theo xe tiếng cối nổ to. Tặng kèm đồng hồ đo tốc độ.",
  },
  {
    id: 35,
    name: "VinBike Himo Z20 (Trợ lực điện)",
    price: 10500000,
    originalPrice: 16000000,
    brand: "Other",
    type: "Touring",
    condition: 92,
    location: "Long Biên, Hà Nội",
    image: "https://himobike.vn/wp-content/uploads/2022/03/z20-900x600-1.jpg",
    postedTime: "1 ngày trước",
    inspectorChecked: true,
    seller: { name: "E-Bike HN", avatar: "https://i.pravatar.cc/150?u=35" },
    year: 2022,
    frame: "Gấp gọn",
    wheel: "20 inch",
    brake: "Phanh đĩa",
    gears: "6 Speed",
    weight: 21.0,
    description:
      "Xe trợ lực điện, pin còn tốt chạy 60km. Gấp gọn bỏ cốp xe hơi. Chìa khóa đầy đủ.",
  },
  {
    id: 36,
    name: "Merida Duke 600",
    price: 7500000,
    originalPrice: 11000000,
    brand: "Merida",
    type: "MTB",
    condition: 93,
    location: "Thủ Đức, TP. HCM",
    image:
      "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=600&q=80",
    postedTime: "3 giờ trước",
    inspectorChecked: false,
    seller: { name: "Tùng MTV", avatar: "https://i.pravatar.cc/150?u=36" },
    year: 2019,
    frame: "17 inch",
    wheel: "26 inch",
    brake: "Phanh dầu Shimano",
    gears: "3x9 Shimano Alivio",
    weight: 13.8,
    description:
      "Dòng Duke nổi tiếng bền bỉ. Xe đã bảo dưỡng, tra dầu mỡ. Mua về chỉ việc chạy.",
  },
  {
    id: 37,
    name: "Look 795 Blade RS",
    price: 115000000,
    originalPrice: 160000000,
    brand: "Look",
    type: "Road",
    condition: 98,
    location: "Tây Hồ, Hà Nội",
    image:
      "https://images.unsplash.com/photo-1511994298241-608e28f14fde?auto=format&fit=crop&w=600&q=80",
    postedTime: "2 ngày trước",
    inspectorChecked: true,
    seller: { name: "Rich Kid", avatar: "https://i.pravatar.cc/150?u=37" },
    year: 2023,
    frame: "S",
    wheel: "Corima Carbon",
    brake: "SRAM Force AXS",
    gears: "2x12 SRAM Force",
    weight: 7.9,
    description:
      "Xe Aero khí động học, màu Mondrian truyền thống của Look. Dây đi âm hoàn toàn.",
  },
  {
    id: 38,
    name: "Cube Reaction C:62",
    price: 28000000,
    originalPrice: 45000000,
    brand: "Other",
    type: "MTB",
    condition: 95,
    location: "Đà Lạt, Lâm Đồng",
    image:
      "https://www.cubestores.co.uk/cdn/shop/files/616100.jpg?v=1727871067&width=1946",
    postedTime: "5 giờ trước",
    inspectorChecked: true,
    seller: { name: "Đạt Đà Lạt", avatar: "https://i.pravatar.cc/150?u=38" },
    year: 2021,
    frame: "17 inch (Carbon)",
    wheel: "29 inch",
    brake: "Phanh dầu XT",
    gears: "1x12 SRAM GX Eagle",
    weight: 10.8,
    description:
      "Xe chuyên leo núi, băng rừng. Khung carbon C:62 cao cấp của Cube. Lốp Schwalbe còn mới.",
  },
  {
    id: 39,
    name: "Totem 1100",
    price: 1200000,
    originalPrice: 2500000,
    brand: "Other",
    type: "City",
    condition: 90,
    location: "Hà Đông, Hà Nội",
    image:
      "https://ugurbisiklet.com/cdn/shop/files/bianchi-via-nirone-7-md-disc-yol-bisikleti-shimano-105-12s-ytb4rsmdrm-39310.png?v=1763197375",
    postedTime: "30 phút trước",
    inspectorChecked: false,
    seller: { name: "Mẹ Bỉm Sữa", avatar: "https://i.pravatar.cc/150?u=39" },
    year: 2022,
    frame: "Nhỏ",
    wheel: "20 inch",
    brake: "Phanh V",
    gears: "6 Speed",
    weight: 10.0,
    description:
      "Xe cho bé 6-9 tuổi. Bé nhà mình lớn rồi nên pass lại. Xe đi giữ gìn.",
  },
  {
    id: 40,
    name: "Cannondale SuperSix EVO",
    price: 68000000,
    originalPrice: 95000000,
    brand: "Cannondale",
    type: "Road",
    condition: 96,
    location: "Q.2, TP. HCM",
    image:
      "https://embed.widencdn.net/img/dorelrl/skbgf6uhzf/800px@1x/C25_C11035U_SuperSix_EVO_Crb_1_RAW_D5.jpg?color=f8f8f8&q=90",
    postedTime: "1 giờ trước",
    inspectorChecked: true,
    seller: {
      name: "Nam Cannondale",
      avatar: "https://i.pravatar.cc/150?u=40",
    },
    year: 2021,
    frame: "51",
    wheel: "HollowGram 35",
    brake: "Phanh đĩa dầu Ultegra",
    gears: "2x11 Shimano Ultegra R8020",
    weight: 7.6,
    description:
      "Dòng xe đua toàn năng. Màu đen nhám cực ngầu. Đã nâng cấp tay lái carbon.",
  },
];
